" for nvim specific do
" if has('nvim')
" endif
call plug#begin('~/.vim/plugged')
 Plug 'dense-analysis/ale'  " support linting, jump to definition and autocomplete
Plug 'airblade/vim-gitgutter'  " git diff in the 'gutter' (sign column). It shows which lines have been added, modified, or removed.
Plug 'aonemd/kuroi.vim'  "a dark theme
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' } " Install binary
Plug 'junegunn/fzf.vim' " Install vim support
Plug 'mattn/emmet-vim'  "
Plug 'morhetz/gruvbox' " retro theme
Plug 'plasticboy/vim-markdown' " markdown support
Plug 'sheerun/vim-polyglot'  "support over 100 languages and load them on demand
Plug 'tpope/vim-repeat'  " enhance vim repeat
Plug 'tpope/vim-unimpaired'  " add pair mapping [b to last buffer, ]b to next buffer

Plug 'tpope/vim-abolish'  " allow case sensitive replace and abbreviation
Plug 'tpope/vim-eunuch'  " Add helpful unix command :Delete :Move :Chmod :Sudo :SudoEdit :Wall
Plug 'tpope/vim-fugitive'  "a git wrapper for vim
Plug 'tpope/vim-surround'  " allow to treat do thing like cs'<q> to change ' to <q> surrounding a text
Plug 'tomtom/tcomment_vim' " allow to comment things out with gc or gcc(line)
Plug 'editorconfig/editorconfig-vim' "allow vim to use editorconfig
Plug 'mbbill/undotree'  " undo tree to visualize vim undo tree

" add convenience on top of netrw for file navigation. '-' to go up. 
" disable info bar on top. 'I' to reenabled
" suffix sort order instead of C biased
" . on a file to prepopulate command line
" 'y.' to yank absolute path
" ~ to go home
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'  " upgrade the existing status bar at the bottom

call plug#end()

" .............................................................................
" basic
" .............................................................................
set exrc "source vimrc automatically when opening a proj directory
set lazyredraw                                     "lazily redraw screen while executing macros, and other commands
set ttyfast                                        "more characters will be sent to the screen for redrawing
set ttimeout                                       "time waited for key press(es) to complete...
set ttimeoutlen=50                                 " ...makes for a faster key response
set backspace=indent,eol,start                     "make backspace behave properly in insert mode
set wildmenu                                       "better menu with completion in command mode
set wildmode=longest:full,full
set scrolloff=8                                    "always show n lines above/below the cursor
set showcmd                                        "display incomplet coc
set cmdheight=2  " Better display for messages
set laststatus=2                                   "always display the status bar
set number                                         "display line numbers
set relativenumber
set cursorline                                     "highlight current line
set colorcolumn=121                                 "display text width column
set autoread  " when running external command with vim, autoreload buffer
" indentation
set autoindent                                     "always set autoindenting on
set smartindent
set tabstop=8 shiftwidth=2 softtabstop=2 "use two spaces for indentation
set incsearch                                      "incremental search highlight
set ignorecase                                     "searches are case insensitive...
set smartcase                                      " ..unless they contain at least one capital letter
set hlsearch                                       "highlight search patterns
set textwidth=0 wrapmargin=0
" See https://github.com/dense-analysis/ale/issues/1700
" :h ale-completion-completeopt-bug
set completeopt=menu,menuone,preview,noselect,noinsert
" The length of time Vim waits after you stop typing before it triggers the
"plugin is governed by the setting updatetime. Default is 4000 which is very
"long
set updatetime=740
set hidden " needed for coc since text edit might fail
" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300
" Don't pass messages to |ins-completion-menu|.
set shortmess+=c
if has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif
set noerrorbells

"" bakcup and history
set noswapfile
set nobackup
set undodir="~/.vim/undodir"
set undofile " vim persist undo to a file in undodir


set t_Co=256                        "enable 256 colors
set background=dark
let g:gruvbox_italic=1 
colorscheme gruvbox

"status line: modifiedflag, charcount, filepercent, filepath
set statusline=%=%m\ %c\ %P\ %f

" Turn on omnicompletion
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" .............................................................................
" netrw
" .............................................................................
let g:netrw_liststyle = 3  " Use the tree view as default. Hit i to change view
let g:netrw_browsex_viewer="open"
let g:netrw_browse_split = 0  " Open netrw by default in the same window
let g:netrw_winsize = 25  " Use 25% of the window width
let g:netrw_altv=1  " if in a netwr view and open a file with v, open to the right instead of left
let g:netrw_alto=1  " if in a netwr view and open a file with o, open to the bottom instead of top


" .............................................................................
" dense-analysis/ale
" .............................................................................
 let g:ale_fixers = {
 \   '*': ['remove_trailing_lines', 'trim_whitespace'],
 \   'javascript': ['prettier', 'eslint'],
 \   'typescript': ['prettier', 'eslint'],
 \   'typescriptreact': ['prettier', 'eslint'],
 \   'css': ['prettier'],
 \   'markdown': ['prettier'],
 \}
 let g:ale_linters = {
 \   'javascript': ['eslint', 'flow-language-server'],
 \}
 let g:ale_linters_ignore = {
 \   'javascript': ['tsserver'],
 \}
 let g:ale_linters_explicit = 1
 let g:ale_linter_aliases = {'jsx': ['css', 'javascript']}
 let g:ale_sign_error = '●'
 let g:ale_sign_warning = '.'
 let g:ale_fix_on_save = 1
 let g:ale_completion_enabled = 1 " use coc
 let g:ale_completion_tsserver_autoimport = 1 " use coc
 let g:ale_javascript_eslint_executable = 'yarn'
 let g:ale_javascript_eslint_options = 'run eslint'
 " ale should set filetype for jsx filetype
augroup FiletypeGroup
    autocmd!
    au BufNewFile,BufRead *.jsx set filetype=javascript.jsx
augroup END

" .............................................................................
" plasticboy/vim-markdown
" .............................................................................
" zr: reduces fold level throughout the buffer
" zR: opens all folds
" zm: increases fold level throughout the buffer
" zM: folds everything all the way
" za: open a fold your cursor is on
" zA: open a fold your cursor is on recursively
" zc: close a fold your cursor is on
" zC: close a fold your cursor is on recursively

let g:vim_markdown_frontmatter = 1
let g:vim_markdown_toml_frontmatter = 1
let g:vim_markdown_json_frontmatter = 1
let g:vim_markdown_strikethrough = 1
let g:vim_markdown_new_list_item_indent = 2
" If you want to have a link like this [link text](link-url) and follow it for editing in vim using the ge command, but have it open the file 'link-url.md' instead of the file 'link-url', then use this option:
let g:vim_markdown_no_extensions_in_markdown = 1
" If you follow a link like this [link text](link-url) using the ge shortcut, this option will automatically save any edits you made before moving you:
let g:vim_markdown_autowrite = 1
let g:vim_markdown_auto_extension_ext = 'txt'


" .............................................................................
" FILE MAP
" .............................................................................
" allow jsonc format
autocmd FileType json syntax match Comment +\/\/.\+$+

" *KEY MAP*

" Space is now another leader key
map <Space> <Leader>


"remove search highlight
nmap <leader>q :nohlsearch<CR>

" window
"" Terminal mode:
tnoremap <M-h> <c-\><c-n><c-w>h
tnoremap <M-j> <c-\><c-n><c-w>j
tnoremap <M-k> <c-\><c-n><c-w>k
tnoremap <M-l> <c-\><c-n><c-w>l
"" Insert mode:
inoremap <M-h> <Esc><c-w>h
inoremap <M-j> <Esc><c-w>j
inoremap <M-k> <Esc><c-w>k
inoremap <M-l> <Esc><c-w>l
"" Visual mode:
vnoremap <M-h> <Esc><c-w>h
vnoremap <M-j> <Esc><c-w>j
vnoremap <M-k> <Esc><c-w>k
vnoremap <M-l> <Esc><c-w>l
"" Normal mode:
nnoremap <M-h> <c-w>h
nnoremap <M-j> <c-w>j
nnoremap <M-k> <c-w>k
nnoremap <M-l> <c-w>l

" buffer
nnoremap <Leader>, :b#<CR>

"fzf
"" implementation that restart rg for each new key in query instead of only
"" first query
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case -- %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)

nnoremap <Leader>ff :Files<CR>
nnoremap <Leader>bb :Buffers<CR>
nnoremap <Leader>fc :Colors<CR>
nnoremap <Leader>fm :Marks<CR>
nnoremap <Leader>fk :Maps<CR>
nnoremap <Leader>fh :History<CR>
nnoremap <Leader>fv :vsplit ~/dotfiles/dots/vimrc<cr>
nnoremap <Leader>sv :source $MYVIMRC<cr>
" search in file
nnoremap <Leader>f/ :BLines<CR>
" search in all opened files
nnoremap <leader>fs :Lines<cr>
" search history
nnoremap <Leader>fS :History/<CR>
nnoremap <Leader><Leader> :GFiles<CR>
nnoremap <Leader>fc :Commands<CR>
nnoremap <Leader>ft :BTags<CR>
nnoremap <leader>fT :Tags<cr>
nnoremap <leader>fh :Helptags<cr>

" fugitive
nnoremap <leader>gg :G<CR>
nnoremap <leader>ga :Gw<CR>
nnoremap <leader>gl :Commits<CR>
nnoremap <leader>gp :Git pull<CR>
nnoremap <leader>gf :Git fetch<CR>
nnoremap <leader>gP :Git push<CR>
nnoremap <leader>g3 :diffget //3<cr>
nnoremap <leader>g2 :diffget //2<cr>

" undo tree
nnoremap <leader>uu :u<CR>
nnoremap <leader>ut :UndotreeToggle<CR>

" terminal
tnoremap <Esc> <C-\><C-n>
tnoremap <M-[> <Esc>

" Move line up or down using option j/k
nnoremap <c-j> :m .+1<CR>==
nnoremap <c-k> :m .-2<CR>==
inoremap <c-j> <Esc>:m .+1<CR>==gi
inoremap <c-k> <Esc>:m .-2<CR>==gi
vnoremap <c-j> :m '>+1<CR>gv=gv
vnoremap <c-k> :m '<-2<CR>gv=gv

" JS
autocmd FileType javascript set formatprg=prettier-eslint\ --stdin
autocmd FileType vue set formatprg=prettier-eslint\ --stdin

" abbrv
iabbrev tmorrow tomorrow
iabbrev tmrrow tomorrow

echo ">^.^<"
