tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bash"
brew "direnv"
brew "entr"
brew "fzf"
brew "git"
brew "gnupg"
brew "jq"
brew "mas"
brew "pinentry-mac" if OS.mac?
brew "neovim"
brew "ranger"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh"
cask "android-studio"
cask "brave-browser"
cask "docker"
cask "dropbox"
cask "font-fantasque-sans-mono"
cask "font-hack"
cask "font-m-plus"
cask "font-source-code-pro"
cask "google-backup-and-sync"
cask "iterm2"
cask "keybase"
cask "notion"
mas "1Password 7", id: 1333542190
mas "Magnet", id: 441258766
mas "Spark", id: 1176895641
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
