#!/bin/zsh
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
dotfiles=("vimrc" "vim" "zshrc" "spacemacs" "gitignore_global")    # list of files/folders to symlink in homedir

##########

# set up space emacs
if [ ! -d "$HOME/.emacs.d" ]; then
  echo 'running'
  rm ~/.emacs #otherwise this will conflict
  git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d
fi
# set up zim
if [ ! -d "$HOME/.zim" ]; then
  git clone --recursive https://github.com/Eriner/zim.git ${ZDOTDIR:-${HOME}}/.zim
  setopt EXTENDED_GLOB
  for template_file ( ${ZDOTDIR:-${HOME}}/.zim/templates/* ); do
       user_file="${ZDOTDIR:-${HOME}}/.${template_file:t}"
         touch ${user_file}
           ( print -n "$(<${template_file})\n$(<${user_file})" >! ${user_file} ) 2>/dev/null
  done
  chsh -s =zsh
fi

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $dotfiles; do
   echo $file $dotfiles
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done

# link nvimrc with vim
#ln -s $dir/vimrc ~/.nvimrc
#ln -s $dir/vim ~/.nvim

