#!/usr/bin/env bash

# add key to agent
if [[ -s "$HOME/ssh-find-agent/ssh-find-agent.sh" ]]; then
  . $HOME/ssh-find-agent/ssh-find-agent.sh
  ssh-find-agent -a
  if [ -z "$SSH_AUTH_SOCK" ]
  then
     eval $(ssh-agent) > /dev/null
     ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'
  fi
     echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
 else
   echo "echo 'WARNING: Could not find ssh-find-agent. Need to run install script!!'"
fi

