#!/usr/bin/env bash

youtube-dl \
  --download-archive ./DOWNLOADED.txt
  --continue \
  --no-overwrites \
  --ignore-errors \
  --add-metadata \
  --write-description \
  --write-info-json \
  --write-annotations \
  --all-subs \
  "$@"
